name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  test:
    uses: ./.github/workflows/django-test.yaml
  deploy:
    needs: test
    name: Test, Build, Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        echo "Deploying!!!!!!!"
